services:
  - type: web
    name: billing-app-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: PORT
        value: "3001"
    autoDeploy: true
    region: oregon
  - type: web
    name: billing-app-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: "https://web-billing-application.onrender.com"
    autoDeploy: true
    region: oregon